add job to indexes issue #285
libreosteo/LibreOsteo pull request #286
Opened 2022-10-14 10:41 UTC by DamyanBG

I added job to indexes as described in the issue #285

2022-10-14 19:10 UTC, jbgury requested changes
Yes it is, it implies for the user to reindexing all patients to have this functionality

2022-10-14 19:10 UTC, jbgury commented on libreosteoweb/templates/search/indexes/libreosteoweb/document_text.txt
> +{{ object.job }}
After reviewing I think it is not the right place to put this field. document_text is to index ... document for patient, and not for patient indexing.
Did  you test successfully this change ? (at least manually test ?)

2022-10-15 06:56 UTC, DamyanBG commented
I made the changes and made manual test - it was sucessful.

2022-10-15 07:50 UTC, jbgury approved these changes

2022-10-15 11:23 UTC, merged